dist: trusty
sudo: false
language: c
compiler:
- gcc
- clang
script:
- make
- make test
- make -C doc
- make install PREFIX=~/.local
- cd /
- recidivm -h
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 recidivm | grep -A 10 -w RECIDIVM

# vim:ts=2 sts=2 sw=2 et
